import React, { useState, useEffect, useCallback, useMemo } from 'react';
import {
  View,
  Text,
  StyleSheet,
  ScrollView,
  TouchableOpacity,
  RefreshControl,
} from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { useRouter } from 'expo-router';
import { Crown, RefreshCw, Check, Sparkles, Leaf } from 'lucide-react-native';
import * as Haptics from 'expo-haptics';
import { useAuthStore } from '@/stores/auth-store';
import { useApiQuery } from '@/hooks/use-api';
import { apiPost } from '@/lib/api';
import { PlanSkeleton } from '@/components/ui/ScreenSkeletons';
import { AnimatedCard } from '@/components/ui/AnimatedCard';
import { InsightCard } from '@/components/ui/InsightCard';
import { lightTheme, categoryColors } from '@/theme/colors';
import { typography } from '@/theme/typography';
import { spacing } from '@/theme/spacing';

// --- Types ---

interface DailyPlanBlock {
  time: string;
  subject: string;
  activity_id?: string;
  title: string;
  duration: number;
  notes?: string;
  completed: boolean;
  outcome_ids?: string[];
}

interface DailyPlan {
  id: string;
  date: string;
  child_id: string;
  child_name?: string;
  blocks: DailyPlanBlock[];
  status: string;
}

interface PlannerData {
  week_start: string;
  week_end?: string;
  days: DailyPlan[];
}

// --- Helpers ---

const DAY_NAMES = ['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun'];

function getDayIndex(dateStr: string): number {
  const d = new Date(dateStr + 'T00:00:00');
  const day = d.getDay();
  return day === 0 ? 6 : day - 1;
}

function getDayAbbrev(dateStr: string): string {
  return DAY_NAMES[getDayIndex(dateStr)];
}

function getDateNumber(dateStr: string): number {
  return new Date(dateStr + 'T00:00:00').getDate();
}

function isToday(dateStr: string): boolean {
  const today = new Date();
  const d = new Date(dateStr + 'T00:00:00');
  return (
    d.getFullYear() === today.getFullYear() &&
    d.getMonth() === today.getMonth() &&
    d.getDate() === today.getDate()
  );
}

function formatDateRange(start: string, end?: string): string {
  const fmt = (s: string) =>
    new Date(s + 'T00:00:00').toLocaleDateString('en-IE', {
      month: 'short',
      day: 'numeric',
    });
  if (!end) return fmt(start);
  return `${fmt(start)} - ${fmt(end)}`;
}

function getCategoryColor(subject: string): string {
  const key = subject?.toLowerCase().replace(/\s+/g, '_') as keyof typeof categoryColors;
  return categoryColors[key] || categoryColors.default;
}

// --- Component ---

export default function PlanScreen() {
  const router = useRouter();
  const effectiveTier = useAuthStore((s) => s.effectiveTier());
  const children = useAuthStore((s) => s.children);
  const family = useAuthStore((s) => s.family);
  const isFree = effectiveTier === 'free';
  const educationApproach = (family as any)?.education_approach || 'blended';

  // ALL hooks before any conditional returns
  const [selectedChild, setSelectedChild] = useState<string | null>(null);
  const [generating, setGenerating] = useState(false);
  const [hasAutoGenerated, setHasAutoGenerated] = useState(false);

  const queryPath = selectedChild ? `/planner?child_id=${selectedChild}` : '/planner';
  const queryKey = selectedChild ? ['planner', selectedChild] : ['planner'];

  const {
    data: plannerData,
    isLoading,
    refetch,
    isRefetching,
  } = useApiQuery<PlannerData>(queryKey, queryPath, { enabled: !isFree });

  const isEmpty =
    !isLoading && plannerData && (!plannerData.days || plannerData.days.length === 0);

  const handleGeneratePlan = useCallback(async () => {
    setGenerating(true);
    try {
      await apiPost('/planner/generate', {});
      Haptics.notificationAsync(Haptics.NotificationFeedbackType.Success);
      await refetch();
    } catch (err) {
      console.error('Failed to generate plan:', err);
    } finally {
      setGenerating(false);
    }
  }, [refetch]);

  // Auto-generate on first empty load
  useEffect(() => {
    if (isEmpty && !generating && !hasAutoGenerated && !isFree) {
      setHasAutoGenerated(true);
      handleGeneratePlan();
    }
  }, [isEmpty, generating, hasAutoGenerated, isFree, handleGeneratePlan]);

  // Build day-grouped data
  const { dayEntries, totalActivities, completedActivities, coveredCategories } =
    useMemo(() => {
      const days = plannerData?.days || [];
      // Build a map of date -> blocks with metadata
      const dateMap: Record<
        string,
        {
          date: string;
          blocks: (DailyPlanBlock & { childName?: string; activityId?: string })[];
        }
      > = {};

      for (const dp of days) {
        if (!dateMap[dp.date]) {
          dateMap[dp.date] = { date: dp.date, blocks: [] };
        }
        for (const b of dp.blocks || []) {
          dateMap[dp.date].blocks.push({
            ...b,
            childName: dp.child_name,
            activityId: b.activity_id,
          });
        }
      }

      // Sort by date
      const sorted = Object.values(dateMap).sort(
        (a, b) => new Date(a.date).getTime() - new Date(b.date).getTime()
      );

      // If we have a week_start but no days for some dates, fill gaps
      const entries = sorted.length > 0 ? sorted : [];

      let total = 0;
      let completed = 0;
      const cats = new Set<string>();

      for (const entry of entries) {
        for (const block of entry.blocks) {
          total++;
          if (block.completed) completed++;
          if (block.subject) cats.add(block.subject.toLowerCase().replace(/\s+/g, '_'));
        }
      }

      return {
        dayEntries: entries,
        totalActivities: total,
        completedActivities: completed,
        coveredCategories: Array.from(cats),
      };
    }, [plannerData]);

  // --- Unschool families see a gentle browse redirect ---
  if (educationApproach === 'unschool') {
    return (
      <SafeAreaView style={styles.safe} edges={['top']}>
        <View style={styles.header}>
          <Text style={styles.title}>Ideas</Text>
        </View>
        <View style={styles.upgradeContainer}>
          <View style={[styles.upgradeIcon, { backgroundColor: `${lightTheme.accent}15` }]}>
            <Leaf size={36} color={lightTheme.accent} />
          </View>
          <Text style={styles.upgradeTitle}>Your family learns through living</Text>
          <Text style={styles.upgradeBody}>
            No schedules, no timetables. Browse activities whenever you want inspiration
            and log what you do to build your family's story.
          </Text>
          <TouchableOpacity
            onPress={() => router.push('/(tabs)/browse')}
            style={[styles.upgradeButton, { backgroundColor: lightTheme.accent }]}
          >
            <Text style={styles.upgradeButtonText}>Browse activities</Text>
          </TouchableOpacity>
        </View>
      </SafeAreaView>
    );
  }

  // --- Free user gate ---
  if (isFree) {
    return (
      <SafeAreaView style={styles.safe} edges={['top']}>
        <View style={styles.header}>
          <Text style={styles.title}>Your Plan</Text>
        </View>
        <View style={styles.upgradeContainer}>
          <View style={styles.upgradeIcon}>
            <Crown size={36} color="#F5A623" />
          </View>
          <Text style={styles.upgradeTitle}>Unlock your weekly plan</Text>
          <Text style={styles.upgradeBody}>
            Get a personalised weekly schedule of activities balanced across
            subjects and energy levels. Available on the Family plan.
          </Text>
          <TouchableOpacity
            onPress={() => router.push('/(stack)/settings/billing' as any)}
            style={styles.upgradeButton}
          >
            <Text style={styles.upgradeButtonText}>Upgrade to Family</Text>
          </TouchableOpacity>
        </View>
      </SafeAreaView>
    );
  }

  // --- Loading / generating ---
  if (isLoading || generating) return <PlanSkeleton />;

  // --- Main render ---
  const progressPercent =
    totalActivities > 0 ? (completedActivities / totalActivities) * 100 : 0;

  return (
    <SafeAreaView style={styles.safe} edges={['top']}>
      {/* Header */}
      <View style={styles.header}>
        <Text style={styles.title}>Your Plan</Text>
        <TouchableOpacity
          onPress={() => {
            Haptics.impactAsync(Haptics.ImpactFeedbackStyle.Light);
            handleGeneratePlan();
          }}
          style={styles.regeneratePill}
          disabled={generating}
        >
          <RefreshCw size={14} color={lightTheme.accent} />
          <Text style={styles.regenerateText}>Regenerate</Text>
        </TouchableOpacity>
      </View>

      {/* Child selector pills */}
      {children.length > 0 && (
        <ScrollView
          horizontal
          showsHorizontalScrollIndicator={false}
          contentContainerStyle={styles.childPillsContainer}
          style={styles.childPillsScroll}
        >
          <TouchableOpacity
            onPress={() => {
              Haptics.selectionAsync();
              setSelectedChild(null);
            }}
            style={[
              styles.childPill,
              selectedChild === null && styles.childPillActive,
            ]}
          >
            <Text
              style={[
                styles.childPillText,
                selectedChild === null && styles.childPillTextActive,
              ]}
            >
              All
            </Text>
          </TouchableOpacity>
          {children.map((child) => (
            <TouchableOpacity
              key={child.id}
              onPress={() => {
                Haptics.selectionAsync();
                setSelectedChild(child.id);
              }}
              style={[
                styles.childPill,
                selectedChild === child.id && styles.childPillActive,
              ]}
            >
              <Text
                style={[
                  styles.childPillText,
                  selectedChild === child.id && styles.childPillTextActive,
                ]}
              >
                {child.name}
              </Text>
            </TouchableOpacity>
          ))}
        </ScrollView>
      )}

      <ScrollView
        contentContainerStyle={styles.scroll}
        showsVerticalScrollIndicator={false}
        refreshControl={
          <RefreshControl
            refreshing={isRefetching}
            onRefresh={refetch}
            tintColor={lightTheme.accent}
          />
        }
      >
        {/* AI Insight */}
        <InsightCard
          type="plan_week"
          context={{
            children,
            planActivities: dayEntries.flatMap((day) =>
              day.blocks.map((b) => ({
                day: day.date,
                title: b.title,
                category: b.subject,
                childName: (b as any).childName,
              }))
            ),
            categoryBreakdown: coveredCategories,
            hedgeScore: 0,
            tierName: effectiveTier,
          }}
          enabled={totalActivities > 0}
        />

        {totalActivities > 0 ? (
          <>
            {/* Plan Overview Card */}
            <AnimatedCard>
              <View style={styles.overviewCard}>
                <View style={styles.overviewHeader}>
                  <Text style={styles.overviewLabel}>This Week</Text>
                  <Text style={styles.overviewDateRange}>
                    {formatDateRange(
                      plannerData?.week_start || '',
                      plannerData?.week_end
                    )}
                  </Text>
                </View>

                {/* Progress bar */}
                <View style={styles.progressBarTrack}>
                  <View
                    style={[
                      styles.progressBarFill,
                      { width: `${progressPercent}%` },
                    ]}
                  />
                </View>

                <View style={styles.overviewFooter}>
                  <Text style={styles.overviewActivities}>
                    Activities: {completedActivities}/{totalActivities} completed
                  </Text>
                  <View style={styles.categoryDots}>
                    {coveredCategories.slice(0, 6).map((cat) => (
                      <View
                        key={cat}
                        style={[
                          styles.categoryDot,
                          {
                            backgroundColor: getCategoryColor(cat),
                          },
                        ]}
                      />
                    ))}
                  </View>
                </View>
              </View>
            </AnimatedCard>

            {/* Day-by-day list */}
            {dayEntries.map((dayEntry) => {
              const todayHighlight = isToday(dayEntry.date);
              const dayAbbrev = getDayAbbrev(dayEntry.date);
              const dateNum = getDateNumber(dayEntry.date);

              return (
                <View key={dayEntry.date} style={styles.dayRow}>
                  {/* Day label column */}
                  <View style={styles.dayLabelCol}>
                    <Text
                      style={[
                        styles.dayAbbrev,
                        todayHighlight && styles.dayAbbrevToday,
                      ]}
                    >
                      {dayAbbrev}
                    </Text>
                    <View
                      style={[
                        styles.dayDateCircle,
                        todayHighlight && styles.dayDateCircleToday,
                      ]}
                    >
                      <Text
                        style={[
                          styles.dayDateNum,
                          todayHighlight && styles.dayDateNumToday,
                        ]}
                      >
                        {dateNum}
                      </Text>
                    </View>
                  </View>

                  {/* Activity cards column */}
                  <View style={styles.dayActivitiesCol}>
                    {dayEntry.blocks.length > 0 ? (
                      dayEntry.blocks.map((block, idx) => {
                        const catColor = getCategoryColor(block.subject);
                        return (
                          <TouchableOpacity
                            key={`${dayEntry.date}-${idx}`}
                            style={styles.activityCard}
                            onPress={() => {
                              if (block.activityId) {
                                router.push(
                                  `/(tabs)/browse/${block.activityId}` as any
                                );
                              }
                            }}
                            activeOpacity={0.7}
                          >
                            {/* Left color bar */}
                            <View
                              style={[
                                styles.activityColorBar,
                                { backgroundColor: catColor },
                              ]}
                            />
                            <View style={styles.activityContent}>
                              <View style={styles.activityTitleRow}>
                                <View
                                  style={[
                                    styles.activityCategoryDot,
                                    { backgroundColor: catColor },
                                  ]}
                                />
                                <Text
                                  style={[
                                    styles.activityTitle,
                                    block.completed &&
                                      styles.activityTitleCompleted,
                                  ]}
                                  numberOfLines={1}
                                >
                                  {block.title}
                                </Text>
                                {block.completed && (
                                  <View style={styles.checkCircle}>
                                    <Check size={12} color="#FFFFFF" />
                                  </View>
                                )}
                              </View>
                              <View style={styles.activityMeta}>
                                <Text style={styles.activityDuration}>
                                  {block.duration} min
                                </Text>
                                {selectedChild === null && block.childName && (
                                  <View style={styles.childTag}>
                                    <Text style={styles.childTagText}>
                                      {block.childName}
                                    </Text>
                                  </View>
                                )}
                              </View>
                            </View>
                          </TouchableOpacity>
                        );
                      })
                    ) : (
                      <Text style={styles.emptyDayText}>No activities</Text>
                    )}
                  </View>
                </View>
              );
            })}
          </>
        ) : (
          /* Empty state */
          <AnimatedCard>
            <View style={styles.emptyCard}>
              <Sparkles size={32} color={lightTheme.accent} />
              <Text style={styles.emptyTitle}>No plan yet</Text>
              <Text style={styles.emptyBody}>
                Tap below to create a personalised weekly plan based on your
                children's ages and interests.
              </Text>
              <TouchableOpacity
                onPress={handleGeneratePlan}
                style={styles.generateCTA}
              >
                <Sparkles size={18} color="#FFFFFF" />
                <Text style={styles.generateCTAText}>Generate my plan</Text>
              </TouchableOpacity>
            </View>
          </AnimatedCard>
        )}
      </ScrollView>
    </SafeAreaView>
  );
}

// --- Styles ---

const styles = StyleSheet.create({
  safe: {
    flex: 1,
    backgroundColor: lightTheme.background,
  },
  header: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: spacing.xl,
    paddingTop: spacing.lg,
    paddingBottom: spacing.md,
  },
  title: {
    ...typography.h2,
    color: lightTheme.text,
  },
  regeneratePill: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    backgroundColor: `${lightTheme.accent}15`,
    borderRadius: 20,
    paddingHorizontal: 14,
    paddingVertical: 8,
  },
  regenerateText: {
    fontSize: 13,
    fontWeight: '600',
    color: lightTheme.accent,
  },

  // Child selector pills
  childPillsScroll: {
    flexGrow: 0,
    marginBottom: spacing.md,
  },
  childPillsContainer: {
    paddingHorizontal: spacing.xl,
    gap: spacing.sm,
  },
  childPill: {
    height: 34,
    borderRadius: 17,
    paddingHorizontal: 16,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: lightTheme.surface,
  },
  childPillActive: {
    backgroundColor: lightTheme.primary,
  },
  childPillText: {
    ...typography.uiSmall,
    fontWeight: '600',
    color: lightTheme.textSecondary,
  },
  childPillTextActive: {
    color: '#FFFFFF',
  },

  scroll: {
    paddingHorizontal: spacing.xl,
    paddingBottom: spacing['6xl'],
    gap: spacing.lg,
  },

  // Overview card
  overviewCard: {
    backgroundColor: lightTheme.surface,
    borderRadius: 16,
    padding: spacing.xl,
    gap: spacing.md,
  },
  overviewHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  overviewLabel: {
    ...typography.uiBold,
    color: lightTheme.text,
  },
  overviewDateRange: {
    ...typography.uiSmall,
    color: lightTheme.textSecondary,
  },
  progressBarTrack: {
    height: 6,
    borderRadius: 3,
    backgroundColor: lightTheme.borderLight,
    overflow: 'hidden',
  },
  progressBarFill: {
    height: '100%',
    borderRadius: 3,
    backgroundColor: lightTheme.accent,
  },
  overviewFooter: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  overviewActivities: {
    ...typography.bodySmall,
    color: lightTheme.textSecondary,
  },
  categoryDots: {
    flexDirection: 'row',
    gap: 4,
  },
  categoryDot: {
    width: 8,
    height: 8,
    borderRadius: 4,
  },

  // Day rows
  dayRow: {
    flexDirection: 'row',
    gap: spacing.md,
  },
  dayLabelCol: {
    width: 44,
    alignItems: 'center',
    paddingTop: 4,
  },
  dayAbbrev: {
    ...typography.uiSmall,
    color: lightTheme.textMuted,
    fontWeight: '600',
  },
  dayAbbrevToday: {
    color: lightTheme.accent,
  },
  dayDateCircle: {
    width: 30,
    height: 30,
    borderRadius: 15,
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: 2,
  },
  dayDateCircleToday: {
    backgroundColor: lightTheme.accent,
  },
  dayDateNum: {
    ...typography.uiBold,
    fontSize: 14,
    color: lightTheme.text,
  },
  dayDateNumToday: {
    color: '#FFFFFF',
  },
  dayActivitiesCol: {
    flex: 1,
    gap: spacing.sm,
    paddingBottom: spacing.md,
  },
  emptyDayText: {
    ...typography.bodySmall,
    color: lightTheme.textMuted,
    paddingVertical: spacing.sm,
  },

  // Activity cards
  activityCard: {
    backgroundColor: lightTheme.surface,
    borderRadius: 12,
    flexDirection: 'row',
    overflow: 'hidden',
  },
  activityColorBar: {
    width: 4,
  },
  activityContent: {
    flex: 1,
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.sm + 2,
    gap: 4,
  },
  activityTitleRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  activityCategoryDot: {
    width: 8,
    height: 8,
    borderRadius: 4,
  },
  activityTitle: {
    ...typography.ui,
    fontWeight: '500',
    color: lightTheme.text,
    flex: 1,
  },
  activityTitleCompleted: {
    textDecorationLine: 'line-through',
    color: lightTheme.textMuted,
  },
  checkCircle: {
    width: 20,
    height: 20,
    borderRadius: 10,
    backgroundColor: lightTheme.success,
    alignItems: 'center',
    justifyContent: 'center',
  },
  activityMeta: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    paddingLeft: 16,
  },
  activityDuration: {
    ...typography.bodySmall,
    color: lightTheme.textSecondary,
  },
  childTag: {
    backgroundColor: `${lightTheme.accent}15`,
    borderRadius: 8,
    paddingHorizontal: 8,
    paddingVertical: 2,
  },
  childTagText: {
    fontSize: 11,
    fontWeight: '600',
    color: lightTheme.accent,
  },

  // Empty state
  emptyCard: {
    backgroundColor: lightTheme.surface,
    borderRadius: 16,
    padding: spacing['2xl'],
    alignItems: 'center',
    gap: spacing.md,
  },
  emptyTitle: {
    ...typography.h3,
    color: lightTheme.text,
  },
  emptyBody: {
    ...typography.body,
    color: lightTheme.textSecondary,
    textAlign: 'center',
    lineHeight: 22,
    maxWidth: 300,
  },
  generateCTA: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    backgroundColor: lightTheme.accent,
    borderRadius: 14,
    paddingHorizontal: spacing['2xl'],
    paddingVertical: 14,
    marginTop: spacing.sm,
  },
  generateCTAText: {
    ...typography.button,
    color: '#FFFFFF',
  },

  // Upgrade
  upgradeContainer: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: spacing['3xl'],
    gap: spacing.lg,
  },
  upgradeIcon: {
    width: 80,
    height: 80,
    borderRadius: 40,
    backgroundColor: '#F5A62315',
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: spacing.sm,
  },
  upgradeTitle: {
    ...typography.h2,
    color: lightTheme.text,
    textAlign: 'center',
  },
  upgradeBody: {
    ...typography.body,
    color: lightTheme.textSecondary,
    textAlign: 'center',
    lineHeight: 22,
    maxWidth: 300,
  },
  upgradeButton: {
    backgroundColor: lightTheme.accent,
    borderRadius: 14,
    paddingHorizontal: spacing['3xl'],
    paddingVertical: 16,
    marginTop: spacing.sm,
  },
  upgradeButtonText: {
    ...typography.button,
    color: '#FFFFFF',
  },
});
