import Link from 'next/link';

export const metadata = {
  title: 'Terms & Conditions - The Hedge',
};

export default function TermsPage() {
  return (
    <div className="min-h-screen bg-parchment">
      <div className="mx-auto max-w-3xl px-6 py-16">
        <Link href="/" className="text-sm text-cat-nature hover:text-forest transition-colors mb-8 inline-block">
          &larr; Back to home
        </Link>

        <h1 className="text-4xl font-bold text-ink mb-2">Terms & Conditions</h1>
        <p className="text-clay mb-12">Last updated: April 2026</p>

        <div className="prose prose-lg max-w-none space-y-8 text-umber">
          <section>
            <h2 className="text-xl font-semibold text-ink">1. About The Hedge</h2>
            <p>The Hedge is a family learning platform that provides personalised, screen-free activity ideas for families with children. By using The Hedge, you agree to these terms.</p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-ink">2. Your account</h2>
            <ul className="list-disc pl-6 space-y-2">
              <li>You must be at least 18 years old to create an account</li>
              <li>You are responsible for maintaining the security of your account</li>
              <li>One family account per household</li>
              <li>You must provide accurate information about your children's ages for appropriate activity recommendations</li>
            </ul>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-ink">3. Subscription plans</h2>
            <p>The Hedge offers three tiers:</p>
            <ul className="list-disc pl-6 space-y-2">
              <li><strong>Free:</strong> Core activity browsing, limited AI suggestions, basic progress tracking</li>
              <li><strong>Family:</strong> Weekly planner, unlimited AI, favourites, full progress tracking</li>
              <li><strong>Educator:</strong> Everything in Family plus curriculum planning, Tusla compliance tools, portfolio management, and attendance tracking</li>
            </ul>
            <p>Paid subscriptions are billed monthly or annually through Stripe. You can cancel at any time from your account settings. Refunds are handled on a case-by-case basis.</p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-ink">4. Activity safety</h2>
            <p>Activities on The Hedge are designed to be safe and age-appropriate. However:</p>
            <ul className="list-disc pl-6 space-y-2">
              <li>Parents and guardians are responsible for supervising children during all activities</li>
              <li>Some activities involve outdoor exploration, cooking, or craft materials - use your judgment about suitability for your child</li>
              <li>Activities are suggestions, not prescriptions - adapt them to your family's needs</li>
              <li>The Hedge is not a substitute for professional educational or medical advice</li>
            </ul>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-ink">5. Homeschool and education features</h2>
            <p>For families using The Hedge for home education:</p>
            <ul className="list-disc pl-6 space-y-2">
              <li>Curriculum alignment is based on the Irish Primary Curriculum (NCCA) and Aistear framework</li>
              <li>Tusla compliance features are provided as tools to assist your record-keeping - they do not guarantee compliance</li>
              <li>You are responsible for meeting your legal obligations regarding home education in Ireland</li>
              <li>Reports generated by The Hedge are for your records and may need to be supplemented for official submissions</li>
            </ul>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-ink">6. Community guidelines</h2>
            <p>When using The Hedge community features:</p>
            <ul className="list-disc pl-6 space-y-2">
              <li>Be respectful and supportive of other families</li>
              <li>Do not share identifying information about children (photos, full names, school names, addresses)</li>
              <li>No commercial promotion or spam</li>
              <li>Report inappropriate content using the report button</li>
              <li>We reserve the right to remove content and suspend accounts that violate these guidelines</li>
            </ul>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-ink">7. Intellectual property</h2>
            <p>Activity content, designs, and the Hedge Score algorithm are the intellectual property of The Hedge. You may not reproduce, distribute, or create derivative works from our content without permission.</p>
            <p>Photos and diary entries you upload remain your property. By uploading them, you grant us permission to store and display them within your family account.</p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-ink">8. Data and privacy</h2>
            <p>Your privacy is important to us. Please read our <Link href="/privacy" className="text-cat-nature hover:underline">Privacy Policy</Link> for details on how we handle your data.</p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-ink">9. Limitation of liability</h2>
            <p>The Hedge is provided "as is". While we strive for accuracy and safety in all activity recommendations, we are not liable for any injury, loss, or damage arising from the use of our platform or participation in suggested activities.</p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-ink">10. Changes to these terms</h2>
            <p>We may update these terms from time to time. We will notify you of significant changes via email or in-app notification. Continued use of The Hedge after changes constitutes acceptance of the updated terms.</p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-ink">11. Contact</h2>
            <p>Questions? Email us at <a href="mailto:hello@thehedge.ie" className="text-cat-nature hover:underline">hello@thehedge.ie</a>.</p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-ink">12. Governing law</h2>
            <p>These terms are governed by the laws of Ireland. Any disputes will be resolved in the courts of Ireland.</p>
          </section>
        </div>
      </div>
    </div>
  );
}
